2018-10-02T11:10:02.379703+00:00 heroku[web.1]: State changed from starting to up
2018-10-02T11:15:08.350963+00:00 heroku[web.1]: Restarting
2018-10-02T11:15:08.351862+00:00 heroku[web.1]: State changed from up to starting
2018-10-02T11:15:09.027289+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2018-10-02T11:15:09.095332+00:00 heroku[web.1]: Process exited with status 143
2018-10-02T11:15:07.496211+00:00 app[api]: Set DATABASE_URL config vars by user pfltriot@gmail.com
2018-10-02T11:15:07.496211+00:00 app[api]: Release v31 created by user pfltriot@gmail.com
2018-10-02T11:15:10.035953+00:00 heroku[web.1]: Starting process with command `npm start`
2018-10-02T11:15:12.083936+00:00 app[web.1]: 
2018-10-02T11:15:12.083958+00:00 app[web.1]: > node-store@1.0.0 start /app
2018-10-02T11:15:12.083961+00:00 app[web.1]: 
2018-10-02T11:15:12.083960+00:00 app[web.1]: > node server/index.js
2018-10-02T11:15:12.288538+00:00 app[web.1]: ready on port 8080
2018-10-02T11:15:13.682760+00:00 heroku[web.1]: State changed from starting to up
2018-10-02T11:25:11.000000+00:00 app[api]: Build started by user pfltriot@gmail.com
2018-10-02T11:25:24.408840+00:00 heroku[web.1]: Restarting
2018-10-02T11:25:24.409369+00:00 heroku[web.1]: State changed from up to starting
2018-10-02T11:25:24.952966+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2018-10-02T11:25:25.022689+00:00 heroku[web.1]: Process exited with status 143
2018-10-02T11:25:22.795063+00:00 app[api]: Deploy 77793c86 by user pfltriot@gmail.com
2018-10-02T11:25:22.795063+00:00 app[api]: Release v32 created by user pfltriot@gmail.com
2018-10-02T11:25:23.000000+00:00 app[api]: Build succeeded
2018-10-02T11:25:26.848273+00:00 heroku[web.1]: Starting process with command `npm start`
2018-10-02T11:25:30.177992+00:00 app[web.1]: 
2018-10-02T11:25:30.178017+00:00 app[web.1]: > node-store@1.0.0 start /app
2018-10-02T11:25:30.178019+00:00 app[web.1]: > node server/index.js
2018-10-02T11:25:30.178020+00:00 app[web.1]: 
2018-10-02T11:25:30.701236+00:00 heroku[web.1]: State changed from starting to up
2018-10-02T11:25:30.703399+00:00 app[web.1]: ready on port 41973
2018-10-02T11:25:30.736091+00:00 app[web.1]: db connected
2018-10-02T11:25:54.739867+00:00 heroku[router]: at=info method=GET path="/" host=pure-taiga-64408.herokuapp.com request_id=8990929c-65b8-40f9-bc65-2977d92ed5c3 fwd="85.143.16.128" dyno=web.1 connect=1ms service=23ms status=200 bytes=207 protocol=https
2018-10-02T11:25:54.729359+00:00 app[web.1]: get request
2018-10-02T11:25:55.515530+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=pure-taiga-64408.herokuapp.com request_id=b42fce42-fb08-4c1c-bfa1-c52935ffe2ed fwd="85.143.16.128" dyno=web.1 connect=1ms service=12ms status=404 bytes=394 protocol=https
2018-10-02T11:26:17.548283+00:00 app[web.1]: post request
2018-10-02T11:26:17.550977+00:00 app[web.1]: { status: 'admin' }
2018-10-02T11:26:17.586788+00:00 heroku[router]: at=info method=POST path="/login" host=pure-taiga-64408.herokuapp.com request_id=39e7f0f2-cd2d-493b-95ec-0eeef1b4ce80 fwd="85.143.16.128" dyno=web.1 connect=1ms service=56ms status=200 bytes=218 protocol=https
2018-10-02T11:26:30.034598+00:00 app[web.1]: events.js:183
2018-10-02T11:26:30.034611+00:00 app[web.1]: throw er; // Unhandled 'error' event
2018-10-02T11:26:30.034613+00:00 app[web.1]: ^
2018-10-02T11:26:30.034614+00:00 app[web.1]: 
2018-10-02T11:26:30.034616+00:00 app[web.1]: Error: Connection lost: The server closed the connection.
2018-10-02T11:26:30.034619+00:00 app[web.1]: at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:112:13)
2018-10-02T11:26:30.034620+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:97:28)
2018-10-02T11:26:30.034622+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)
2018-10-02T11:26:30.034623+00:00 app[web.1]: at emitNone (events.js:111:20)
2018-10-02T11:26:30.034625+00:00 app[web.1]: at Socket.emit (events.js:208:7)
2018-10-02T11:26:30.034627+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1064:12)
2018-10-02T11:26:30.034628+00:00 app[web.1]: at _combinedTickCallback (internal/process/next_tick.js:139:11)
2018-10-02T11:26:30.034630+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:181:9)
2018-10-02T11:26:30.068389+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-10-02T11:26:30.068919+00:00 app[web.1]: npm ERR! errno 1
2018-10-02T11:26:30.075100+00:00 app[web.1]: npm ERR! node-store@1.0.0 start: `node server/index.js`
2018-10-02T11:26:30.075301+00:00 app[web.1]: npm ERR! Exit status 1
2018-10-02T11:26:30.075808+00:00 app[web.1]: npm ERR! Failed at the node-store@1.0.0 start script.
2018-10-02T11:26:30.075605+00:00 app[web.1]: npm ERR!
2018-10-02T11:26:30.075998+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-10-02T11:26:30.089796+00:00 app[web.1]: 
2018-10-02T11:26:30.091031+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2018-10-02T11:26:30.091034+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-10-02T11_26_30_078Z-debug.log
2018-10-02T11:26:30.198084+00:00 heroku[web.1]: State changed from up to crashed
2018-10-02T11:26:30.199859+00:00 heroku[web.1]: State changed from crashed to starting
2018-10-02T11:26:30.179771+00:00 heroku[web.1]: Process exited with status 1
2018-10-02T11:26:31.909039+00:00 heroku[web.1]: Starting process with command `npm start`
2018-10-02T11:26:33.644630+00:00 app[web.1]: 
2018-10-02T11:26:33.644646+00:00 app[web.1]: > node-store@1.0.0 start /app
2018-10-02T11:26:33.644647+00:00 app[web.1]: > node server/index.js
2018-10-02T11:26:33.644649+00:00 app[web.1]: 
2018-10-02T11:26:33.927478+00:00 app[web.1]: db connected
2018-10-02T11:26:33.907069+00:00 app[web.1]: ready on port 39732
2018-10-02T11:26:34.054113+00:00 heroku[web.1]: State changed from starting to up
2018-10-02T11:27:05.575285+00:00 heroku[router]: at=info method=POST path="/login" host=pure-taiga-64408.herokuapp.com request_id=f03118a4-9a9a-45d2-b117-892fb10d39a4 fwd="85.143.16.128" dyno=web.1 connect=1ms service=24ms status=200 bytes=218 protocol=https
2018-10-02T11:27:05.566862+00:00 app[web.1]: post request
2018-10-02T11:27:05.568524+00:00 app[web.1]: { status: 'admin' }
2018-10-02T11:27:33.032408+00:00 app[web.1]: events.js:183
2018-10-02T11:27:33.032426+00:00 app[web.1]: throw er; // Unhandled 'error' event
2018-10-02T11:27:33.032429+00:00 app[web.1]: ^
2018-10-02T11:27:33.032430+00:00 app[web.1]: 
2018-10-02T11:27:33.032433+00:00 app[web.1]: Error: Connection lost: The server closed the connection.
2018-10-02T11:27:33.032435+00:00 app[web.1]: at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:112:13)
2018-10-02T11:27:33.032437+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:97:28)
2018-10-02T11:27:33.032439+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)
2018-10-02T11:27:33.032440+00:00 app[web.1]: at emitNone (events.js:111:20)
2018-10-02T11:27:33.032442+00:00 app[web.1]: at Socket.emit (events.js:208:7)
2018-10-02T11:27:33.032444+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1064:12)
2018-10-02T11:27:33.032446+00:00 app[web.1]: at _combinedTickCallback (internal/process/next_tick.js:139:11)
2018-10-02T11:27:33.032448+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:181:9)
2018-10-02T11:27:33.039895+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-10-02T11:27:33.040363+00:00 app[web.1]: npm ERR! errno 1
2018-10-02T11:27:33.042100+00:00 app[web.1]: npm ERR! node-store@1.0.0 start: `node server/index.js`
2018-10-02T11:27:33.042296+00:00 app[web.1]: npm ERR! Exit status 1
2018-10-02T11:27:33.042570+00:00 app[web.1]: npm ERR!
2018-10-02T11:27:33.042770+00:00 app[web.1]: npm ERR! Failed at the node-store@1.0.0 start script.
2018-10-02T11:27:33.042970+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-10-02T11:27:33.049459+00:00 app[web.1]: 
2018-10-02T11:27:33.049603+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2018-10-02T11:27:33.049720+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-10-02T11_27_33_044Z-debug.log
2018-10-02T11:27:33.110167+00:00 heroku[web.1]: Process exited with status 1
2018-10-02T11:27:33.141568+00:00 heroku[web.1]: State changed from up to crashed
2018-10-02T11:27:56.243041+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/login" host=pure-taiga-64408.herokuapp.com request_id=7f2c2c6d-9979-4dfc-8fc5-e212118130ae fwd="85.143.16.128" dyno= connect= service= status=503 bytes= protocol=https
2018-10-02T11:28:56.993850+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=pure-taiga-64408.herokuapp.com request_id=df35adc7-1768-43b4-83b1-577575795a51 fwd="85.143.16.128" dyno= connect= service= status=503 bytes= protocol=https
